### ISSUE TITLE
Color ordered list just like unordered list

### ISSUE THREAD

**Issue by akerbos** [grrinchas/aliquam#5]
I stumbled over a little design inconsistency: ordered list item labels are black, not orange like those of unordered lists.

Here's a fix (via [kdgregory](http://stackoverflow.com/a/489002/539599) on Stack Overflow):

```css
article > ol { 
  counter-reset: item; 
}
article > ol li { 
  display: block; 
}
article > ol li:before {
  content: counter(item) ".\0020";
  counter-increment: item;
  color: $color-orange;
  margin-right: $l-h-baseline / 6;
}
```

I'm not too sure about the spacing, but counting and coloring works.
